// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFe-p5sps_1wuSI-bbxk9a3Z3pyjyRTW4',
    appId: '1:1054069052055:android:89ba1dd785b27fc0e38fd2',
    messagingSenderId: '1054069052055',
    projectId: 'eatseasy-49a0d',
    storageBucket: 'eatseasy-49a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaI5-5zIkz1ekrZLm-yauRzKgvcfUZut4',
    appId: '1:789801624091:ios:05237d16ad76e25ca94ebe',
    messagingSenderId: '789801624091',
    projectId: 'eatseasy-food-apps',
    storageBucket: 'eatseasy-food-apps.appspot.com',
    iosBundleId: 'com.szacheo.eatseasy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD0qJ8g9xMPeYh-rFGmgYjBTCezWWwy6AY",
    authDomain: "eatseasy-49a0d.firebaseapp.com",
    projectId: "eatseasy-49a0d",
    storageBucket: "eatseasy-49a0d.firebasestorage.app",
    messagingSenderId: "1054069052055",
    appId: "1:1054069052055:web:edf17a48746c5547e38fd2"
  );

}